[JPCFM-3925]add playwright.yml step for goldminers tests

diff --git a/.github/workflows/playwright.yml b/.github/workflows/playwright.yml
--- a/.github/workflows/playwright.yml
+++ b/.github/workflows/playwright.yml
@@ -176,3 +176,37 @@ jobs:
           bg_color: '#FF0000'
           slack_token: ${{ secrets.GH_SLACK_TOKEN }}
           environment: ${{ needs.extract-environment.outputs.environment }}
+
+
+  notify-gm-test-failures:
+      name: Notify GM Test Failures
+      runs-on: [ self-hosted, jamf-ubuntu-latest ]
+      needs: [ test ]
+      if: ${{ failure() }}
+      steps:
+        - uses: actions/download-artifact@v4
+          with:
+            name: results.json
+        - id: extract
+          name: Extract Playwright Test Results
+          run: |
+            if ! [ -f results.json ]; then
+              echo "results.json not found"
+              exit 1
+            fi
+  
+            has_failure=$(jq -r '
+            .suites[]
+            | select(.title | test("goldminers"; "i"))
+            | .specs[]
+            | select(.ok == false)
+            | .title
+            ' results.json)
+  
+            if [ -n "$has_failure" ]; then
+              echo "Found failing specs in 'goldminers' suite:"
+              echo "$has_failure"
+              exit 1
+            else
+              echo "No failed specs found in 'goldminers' suites."
+            fi
